PubkeyAuthentication yes
PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
AuthenticationMethods publickey
AllowUsers claw
X11Forwarding no
AllowTcpForwarding no
AllowAgentForwarding no
AllowStreamLocalForwarding no
DisableForwarding yes
PermitOpen none
PermitListen none
PermitTunnel no
GatewayPorts no
PermitUserEnvironment no
MaxAuthTries 3
